# Generated by Django 5.2.17 on 2026-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5),
        ),
    ]
