# Generated by Django 5.2.17 on 2026-08-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('generic_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('strength', models.CharField(blank=True, max_length=60)),
                ('form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('cream', 'Cream'), ('patch', 'Patch'), ('other', 'Other')], default='tablet', max_length=20)),
                ('category', models.CharField(blank=True, db_index=True, max_length=80)),
                ('usage', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'catalog medicine',
                'verbose_name_plural': 'catalog medicines',
                'ordering': ['name', 'strength'],
                'indexes': [models.Index(fields=['name', 'strength'], name='catalog_cat_name_dc30e6_idx'), models.Index(fields=['generic_name'], name='catalog_cat_generic_784cbb_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'strength', 'form'), name='unique_catalog_presentation')],
            },
        ),
    ]
