# Generated by Django 5.2.17 on 2026-08-19 08:22

import caregivers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0002_medicine_catalog_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caregiver_email', models.EmailField(max_length=254)),
                ('caregiver_name', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=60)),
                ('invite_code', models.CharField(default=caregivers.models.make_invite_code, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('alert_on_missed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_links', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caregiver link',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CaregiverAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('kind', models.CharField(choices=[('missed', 'Dose missed'), ('unconfirmed', 'Dose not confirmed')], default='missed', max_length=12)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='medicines.medicine')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='caregivers.caregiverlink')),
            ],
            options={
                'verbose_name': 'caregiver alert',
                'ordering': ['-scheduled_date', '-scheduled_time', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='caregiverlink',
            index=models.Index(fields=['caregiver', 'status'], name='caregivers__caregiv_c1cf3f_idx'),
        ),
        migrations.AddIndex(
            model_name='caregiverlink',
            index=models.Index(fields=['patient', 'status'], name='caregivers__patient_e4a004_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregiverlink',
            constraint=models.UniqueConstraint(fields=('patient', 'caregiver_email'), name='unique_caregiver_per_patient'),
        ),
        migrations.AddIndex(
            model_name='caregiveralert',
            index=models.Index(fields=['link', 'read_at'], name='caregivers__link_id_b2a5da_idx'),
        ),
        migrations.AddConstraint(
            model_name='caregiveralert',
            constraint=models.UniqueConstraint(fields=('link', 'medicine_name', 'scheduled_date', 'scheduled_time'), name='unique_alert_per_dose'),
        ),
    ]
