# Generated by Django 5.2.17 on 2026-08-19 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('medicines', '0002_medicine_catalog_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='meal_relation',
            field=models.CharField(choices=[('none', 'No preference'), ('before', 'Before meal'), ('with', 'With meal'), ('after', 'After meal')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='medicine',
            name='routine',
            field=models.CharField(choices=[('anytime', 'Any time'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('bedtime', 'Bedtime')], default='anytime', max_length=16),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['user', 'routine'], name='medicines_m_user_id_10acfb_idx'),
        ),
    ]
